name: safar_suraksha
description: Flutter app for Digital Tourist ID & Safety Platform
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  go_router: ^14.2.7
  socket_io_client: ^3.1.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

transitive dependencies:
  characters: ^1.4.0
  material_color_utilities: ^0.11.1
  meta: ^1.16.0

transitive dev_dependencies:
  test_api: ^0.7.6


flutter:
  uses-material-design: true

